spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: html
    prefix: classpath:/templates/
    suffix: .html
#  redis:
#    database: 0
#    host: 192.168.10.235
#    port: 6379
#    password: gk_redis
#    lettuce:
#      pool:
#        max-active: 8   #最大活跃连接数 默认8
#        max-idle: 8     #最大空闲连接数 默认8
#        min-idle: 0     #最小空闲连接数 默认0     
#        max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）
          
server:
  port: 8888
  

